package view;

import dao.ConnectionFactory;
import dao.LavagemDAO;
import model.Lavagem;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class LavagemView extends javax.swing.JFrame {
    
    private Connection conn;
    private PreparedStatement stmt;
    private Statement st;
    private ResultSet rs;
    
    Lavagem pro = new Lavagem();
    LavagemDAO prd = new LavagemDAO();

    public LavagemView() {
        initComponents();
        setLocationRelativeTo(null);
        
        conn = new ConnectionFactory().getConexao();        
        this.populaJComboBox();
                        
    }
    public void populaJComboBox(){
        String sql = "SELECT *FROM servicos_tb";
        
        try {
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            
            while (rs.next()) {
                jcbLavagem.addItem(rs.getString("descricao"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbLavagem = new javax.swing.JComboBox();
        btVerificar = new javax.swing.JButton();
        btCancelarLavagem = new javax.swing.JButton();
        btSalvarLavagem = new javax.swing.JButton();
        tfFuncionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btLimparLavagem = new javax.swing.JButton();
        btExcluirLavagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jcbLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLavagemActionPerformed(evt);
            }
        });

        btVerificar.setText("Verificar");
        btVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarActionPerformed(evt);
            }
        });

        btCancelarLavagem.setText("Cancelar");
        btCancelarLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarLavagemActionPerformed(evt);
            }
        });

        btSalvarLavagem.setText("Salvar");
        btSalvarLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarLavagemActionPerformed(evt);
            }
        });

        tfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Placa");

        jLabel2.setText("Serviço");

        jLabel3.setText("Funcionário");

        jLabel4.setText("Código");

        jTextField2.setEditable(false);

        btLimparLavagem.setText("Limpar");
        btLimparLavagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparLavagemActionPerformed(evt);
            }
        });

        btExcluirLavagem.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btCancelarLavagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbLavagem, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btVerificar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btLimparLavagem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btExcluirLavagem)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalvarLavagem)))))
                .addGap(33, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbLavagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btVerificar)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLimparLavagem)
                            .addComponent(btExcluirLavagem)
                            .addComponent(btSalvarLavagem)
                            .addComponent(btCancelarLavagem))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarActionPerformed
        // TODO add your handling code here:
        if (jcbLavagem.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha as opções abaixo.", null, WIDTH);
        } else {
            JOptionPane.showMessageDialog(null, "Opçãos correta.", null, WIDTH);
        }
    }//GEN-LAST:event_btVerificarActionPerformed

    private void jcbLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLavagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLavagemActionPerformed

    private void btCancelarLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarLavagemActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarLavagemActionPerformed

    private void btSalvarLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarLavagemActionPerformed
        // TODO add your handling code here:
        if (jcbLavagem.getSelectedItem().equals("")){
            pro.getServico().getVeiculo().setPlaca_veiculo(jtfPlaca.getText());       
            //pro.setTipo_lavagem((String) jcbLavagem.getSelectedItem());
            pro.getServico().getFuncionario().setNome_funcionario(tfFuncionario.getText());
            prd.inserir(pro);
        }
        
        JOptionPane.showMessageDialog(this, "Serviço de Lavagem concluída");

    }//GEN-LAST:event_btSalvarLavagemActionPerformed

    private void tfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFuncionarioActionPerformed

    private void btLimparLavagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparLavagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparLavagemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarLavagem;
    private javax.swing.JButton btExcluirLavagem;
    private javax.swing.JButton btLimparLavagem;
    private javax.swing.JButton btSalvarLavagem;
    private javax.swing.JButton btVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox jcbLavagem;
    private javax.swing.JTextField jtfPlaca;
    private javax.swing.JTextField tfFuncionario;
    // End of variables declaration//GEN-END:variables
}
